# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpita-de <tpita-de@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/11/14 05:56:57 by tomasrpita        #+#    #+#              #
#    Updated: 2019/11/24 13:58:23 by tpita-de         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=libft.a

SRCS=ft_atoi.c     ft_isascii.c  ft_memcmp.c   ft_strdup.c   ft_strnstr.c \
	ft_bzero.c    ft_isdigit.c  ft_memcpy.c   ft_strlcat.c  ft_strrchr.c \
	ft_calloc.c   ft_isprint.c  ft_memmove.c  ft_strlcpy.c  ft_tolower.c \
	ft_isalnum.c  ft_memccpy.c  ft_memset.c   ft_strlen.c   ft_toupper.c \
	ft_isalpha.c  ft_memchr.c   ft_strchr.c   ft_strncmp.c  ft_substr.c \
	ft_strjoin.c  ft_strtrim.c  ft_split.c    ft_itoa.c		ft_strmapi.c \
	ft_putchar_fd.c  ft_putstr_fd.c  ft_putendl_fd.c  ft_putnbr_fd.c \
	ft_lstnew.c  ft_lstadd_front.c  ft_lstsize.c  ft_lstlast.c  \
	ft_lstadd_back.c

OBJETCS=ft_atoi.o     ft_isascii.o  ft_memcmp.o   ft_strdup.o   ft_strnstr.o \
	ft_bzero.o    ft_isdigit.o  ft_memcpy.o   ft_strlcat.o  ft_strrchr.o \
	ft_calloc.o   ft_isprint.o  ft_memmove.o  ft_strlcpy.o  ft_tolower.o \
	ft_isalnum.o  ft_memccpy.o  ft_memset.o   ft_strlen.o   ft_toupper.o \
	ft_isalpha.o  ft_memchr.o   ft_strchr.o   ft_strncmp.o  ft_substr.o \
	ft_strjoin.o  ft_strtrim.o  ft_split.o    ft_itoa.o		ft_strmapi.o \
	ft_putchar_fd.o  ft_putstr_fd.o  ft_putendl_fd.o  ft_putnbr_fd.o \
	ft_lstnew.o  ft_lstadd_front.o  ft_lstsize.o  ft_lstlast.o  \
	ft_lstadd_back.o

INCLUDES=./

all: $(NAME)

$(NAME): $(SRCS) libft.h
	@gcc -Wall -Wextra -Werror -I$(INCLUDES) -c $(SRCS)
	@ar rc $(NAME) $(OBJETCS)
	@ranlib $(NAME)

clean:
	@/bin/rm -f $(OBJETCS)

fclean: clean
	@/bin/rm -f $(NAME)

re: fclean all